Repository AGH-Narzedzia-Informatyczne-2023-2024/JadloPlan, pull requests merged in 2023-11, with the labels that each got.

#8 Create mar.py
  mar.py
Labels: enhancement

#9 Testowy kalkulator makroskładników
  kalkulator.py
Labels: Test

#12 Create Favourite.py
  Favourite.py
Labels: good first issue

#14 Dodano plan tygodnia
  plandnia.py
Labels: good first issue

#13 Lista zakupów
  lista_zakupów.py
Labels: enhancement

#10 Prosty program dodający komentarze i oceny
  commenting.py
Labels: good first issue
